"""v1 baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-06-14 09:15:37.591277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The default media subtypes every fresh install starts with. SQLAlchemy's
# Enum type persists the Python enum member's *name* (e.g. "MUSIC",
# "PHYSICAL"), not its value, so that's what's inserted here.
_DEFAULT_MEDIA_SUBTYPES = [
    {"name": "CD", "category": "MUSIC", "supertype": "PHYSICAL", "sort_order": 0},
    {"name": "Music", "category": "MUSIC", "supertype": "DIGITAL", "sort_order": 0},
    {"name": "DVD", "category": "FILMS_TV", "supertype": "PHYSICAL", "sort_order": 0},
    {"name": "Blu-ray", "category": "FILMS_TV", "supertype": "PHYSICAL", "sort_order": 1},
    {"name": "Film", "category": "FILMS_TV", "supertype": "DIGITAL", "sort_order": 0},
    {"name": "TV Series", "category": "FILMS_TV", "supertype": "DIGITAL", "sort_order": 1},
    {"name": "Book", "category": "BOOKS", "supertype": "PHYSICAL", "sort_order": 0},
    {"name": "Graphic Novel", "category": "BOOKS", "supertype": "PHYSICAL", "sort_order": 1},
    {"name": "eBook", "category": "BOOKS", "supertype": "DIGITAL", "sort_order": 0},
    {"name": "Audiobook", "category": "BOOKS", "supertype": "DIGITAL", "sort_order": 1},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon_key', sa.String(length=50), nullable=True),
    sa.Column('icon_path', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('media_subtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('MUSIC', 'FILMS_TV', 'BOOKS', name='mediacategory'), nullable=False),
    sa.Column('supertype', sa.Enum('PHYSICAL', 'DIGITAL', name='supertype'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'supertype', 'name', name='uq_media_subtype_category_supertype_name')
    )
    with op.batch_alter_table('media_subtypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_subtypes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_subtypes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_subtypes_supertype'), ['supertype'], unique=False)

    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_key', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('can_add_items', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('can_manage_locations', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('can_manage_platforms', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('can_manage_media_types', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_path', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('edition', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('artist', sa.String(length=300), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=300), nullable=True),
    sa.Column('studio', sa.String(length=300), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('cast_list', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=100), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('openlibrary_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('media_subtype_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('seasons_owned', sa.String(length=100), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_subtype_id'], ['media_subtypes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_media_subtype_id'), ['media_subtype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_musicbrainz_id'), ['musicbrainz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_openlibrary_id'), ['openlibrary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_year'), ['year'], unique=False)

    op.create_table('plex_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_plex_config_singleton'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plex_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plex_config_id'), ['id'], unique=False)

    op.create_table('plex_library_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=300), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('MUSIC', 'FILMS_TV', 'BOOKS', name='mediacategory'), nullable=False),
    sa.Column('media_subtype_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_subtype_id'], ['media_subtypes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_key')
    )
    with op.batch_alter_table('plex_library_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plex_library_mappings_id'), ['id'], unique=False)

    op.create_table('item_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_a_id', sa.Integer(), nullable=False),
    sa.Column('item_b_id', sa.Integer(), nullable=False),
    sa.Column('matched_via', sa.Enum('AUTO', 'MANUAL', name='linkmatchtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('item_a_id < item_b_id', name='ck_item_links_ordered'),
    sa.ForeignKeyConstraint(['item_a_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_b_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_a_id', 'item_b_id', name='uq_item_links_pair')
    )
    with op.batch_alter_table('item_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_links_item_a_id'), ['item_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_links_item_b_id'), ['item_b_id'], unique=False)

    # ### end Alembic commands ###

    media_subtypes = sa.table(
        'media_subtypes',
        sa.column('name', sa.String),
        sa.column('category', sa.String),
        sa.column('supertype', sa.String),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(media_subtypes, _DEFAULT_MEDIA_SUBTYPES)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_links_item_b_id'))
        batch_op.drop_index(batch_op.f('ix_item_links_item_a_id'))
        batch_op.drop_index(batch_op.f('ix_item_links_id'))

    op.drop_table('item_links')
    with op.batch_alter_table('plex_library_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plex_library_mappings_id'))

    op.drop_table('plex_library_mappings')
    with op.batch_alter_table('plex_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plex_config_id'))

    op.drop_table('plex_config')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_year'))
        batch_op.drop_index(batch_op.f('ix_media_items_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_title'))
        batch_op.drop_index(batch_op.f('ix_media_items_platform_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_openlibrary_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_musicbrainz_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_media_subtype_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_location_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_isbn'))
        batch_op.drop_index(batch_op.f('ix_media_items_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_barcode'))

    op.drop_table('media_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_id'))

    op.drop_table('platforms')
    with op.batch_alter_table('media_subtypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_subtypes_supertype'))
        batch_op.drop_index(batch_op.f('ix_media_subtypes_id'))
        batch_op.drop_index(batch_op.f('ix_media_subtypes_category'))

    op.drop_table('media_subtypes')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
